export interface RenderOptions {
  template: string;
  data: Record<string, unknown>;
  includeBranding?: boolean;
}

export interface RenderResult {
  html: string;
  size: number;
}

export interface TemplateComponent {
  (props: Record<string, unknown>): string;
}

export function parseTemplate(template: string): TemplateComponent {
  return function (data: Record<string, unknown>): string {
    let html = template;

    const encodeHtml = (str: string): string => {
      return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
    };

    const flatten = (obj: unknown): string => {
      if (obj === null || obj === undefined) return '';
      if (typeof obj === 'string' || typeof obj === 'number' || typeof obj === 'boolean') return String(obj);
      if (Array.isArray(obj)) return obj.map(flatten).join('');
      if (typeof obj === 'object') {
        return Object.entries(obj as Record<string, unknown>)
          .map(([key, value]) => `${key}: ${flatten(value)}`)
          .join(', ');
      }
      return String(obj);
    };

    const scope: Record<string, unknown> = { ...data };

    const processConditionals = (): boolean => {
      let changed = false;
      const ifRegex = /\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g;

      html = html.replace(ifRegex, (_: string, propName: string, content: string) => {
        const value = scope[propName];
        if (value && (Array.isArray(value) ? value.length > 0 : value)) {
          changed = true;
          return content;
        }
        return '';
      });

      return changed;
    };

    const processLoops = (): boolean => {
      let changed = false;
      const loopRegex = /\{\{#each\s+(\w+)\s+as\s+(\w+)(?:\s*,\s*(\w+))?\}\}([\s\S]*?)\{\{\/each\}\}/g;

      html = html.replace(loopRegex, (_: string, arrayName: string, itemName: string, indexName: string, content: string) => {
        const array = scope[arrayName];
        if (Array.isArray(array)) {
          changed = true;
          return array
            .map((item, idx) => {
              let itemContent = content;
              if (typeof item === 'object' && item !== null) {
                itemContent = itemContent.replace(new RegExp(`\\{\\{${itemName}\\.(\\w+)\\}\\}`, 'g'), (_: string, prop: string) => {
                  return flatten((item as Record<string, unknown>)[prop]);
                });
              } else {
                itemContent = itemContent.replace(new RegExp(`\\{\\{${itemName}\\}\\}`, 'g'), String(item));
              }
              if (indexName) {
                itemContent = itemContent.replace(new RegExp(`\\{\\{${indexName}\\}\\}`, 'g'), String(idx));
              }
              return itemContent;
            })
            .join('');
        }
        return '';
      });

      return changed;
    };

    const processInterpolations = (): boolean => {
      let changed = false;

    const propRegex = /\{\{(\w+(?:\.\w+)*)\}\}/g;
    html = html.replace(propRegex, (_: string, path: string) => {
        changed = true;
        const parts = path.split('.');
        let value: unknown = scope;
        for (const part of parts) {
          if (value && typeof value === 'object' && part in (value as Record<string, unknown>)) {
            value = (value as Record<string, unknown>)[part];
          } else {
            return `{{${path}}}`;
          }
        }
        return String(flatten(value) ?? '');
      });

      return changed;
    };

    let iterations = 0;
    const maxIterations = 10;

    while (iterations < maxIterations) {
      let modified = false;

      modified = processConditionals() || modified;
      modified = processLoops() || modified;
      modified = processInterpolations() || modified;

      if (!modified) break;
      iterations++;
    }

    return html;
  };
}

export function renderTemplate(options: RenderOptions): RenderResult {
  const { template, data, includeBranding = true } = options;

  const brandingHtml = `
    <div style="display: flex; align-items: center; justify-content: space-between; padding: 20px 40px; border-bottom: 2px solid #1f2937;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect width="40" height="40" rx="8" fill="#1f2937"/>
          <path d="M20 10L28 18V28H12V18L20 10Z" stroke="white" stroke-width="2" fill="none"/>
          <circle cx="20" cy="22" r="3" fill="white"/>
        </svg>
        <span style="font-size: 20px; font-weight: 600; color: #1f2937;">ShipSec Studio</span>
      </div>
      <div style="font-size: 12px; color: #6b7280;">Generated by ShipSec Studio</div>
    </div>
  `;

  const footerHtml = `
    <div style="padding: 20px 40px; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; font-size: 11px; color: #6b7280;">
      <div>Generated by ShipSec Studio - ${new Date().toLocaleDateString()}</div>
      <div>Confidential - For Authorized Recipients Only</div>
    </div>
  `;

  const templateFn = parseTemplate(template);
  const bodyHtml = templateFn(data);

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ShipSec Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1f2937; background: #ffffff; }
    .container { max-width: 900px; margin: 0 auto; padding: 40px; }
    h1 { font-size: 32px; font-weight: 700; margin-bottom: 8px; color: #1f2937; }
    h2 { font-size: 24px; font-weight: 600; margin-top: 32px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #e5e7eb; }
    h3 { font-size: 18px; font-weight: 600; margin-bottom: 8px; }
    .meta { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 16px; margin: 24px 0; }
    .summary-card { padding: 16px; border-radius: 8px; text-align: center; }
    .summary-card.critical { background: #fef2f2; border: 1px solid #fecaca; }
    .summary-card.high { background: #fff7ed; border: 1px solid #fed7aa; }
    .summary-card.medium { background: #fefce8; border: 1px solid #fef08a; }
    .summary-card.low { background: #f0fdf4; border: 1px solid #bbf7d0; }
    .summary-card.info { background: #eff6ff; border: 1px solid #bfdbfe; }
    .summary-count { font-size: 32px; font-weight: 700; }
    .summary-label { font-size: 13px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th { text-align: left; padding: 12px; background: #f9fafb; border-bottom: 2px solid #e5e7eb; font-weight: 600; font-size: 13px; color: #374151; }
    td { padding: 12px; border-bottom: 1px solid #e5e7eb; }
    .finding { margin-bottom: 24px; padding: 16px; border-left: 4px solid #ccc; background: #f9fafb; border-radius: 0 8px 8px 0; }
    .finding.critical { border-left-color: #DC2626; }
    .finding.high { border-left-color: #EA580C; }
    .finding.medium { border-left-color: #CA8A04; }
    .finding.low { border-left-color: #16A34A; }
    .finding.info { border-left-color: #2563EB; }
    .severity-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; color: white; text-transform: uppercase; }
    .severity-badge.critical { background: #DC2626; }
    .severity-badge.high { background: #EA580C; }
    .severity-badge.medium { background: #CA8A04; }
    .severity-badge.low { background: #16A34A; }
    .severity-badge.info { background: #2563EB; }
    .page-break { page-break-before: always; }
    @media print {
      body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  ${includeBranding ? brandingHtml : ''}
  ${bodyHtml}
  ${includeBranding ? footerHtml : ''}
</body>
</html>`;

  const encoder = new TextEncoder();
  const size = encoder.encode(fullHtml).length;

  return {
    html: fullHtml,
    size,
  };
}

export const SEVERITY_COLORS: Record<string, string> = {
  critical: '#DC2626',
  high: '#EA580C',
  medium: '#CA8A04',
  low: '#16A34A',
  info: '#2563EB',
};

export function generateDefaultTemplate(): string {
  return `
<div class="container">
  <h1>{{metadata.reportTitle || 'Security Assessment Report'}}</h1>
  <p class="meta">
    <strong>Client:</strong> {{metadata.clientName || 'Not specified'}} &nbsp;|&nbsp;
    <strong>Date:</strong> {{metadata.date || new Date().toISOString().split('T')[0]}} &nbsp;|&nbsp;
    <strong>Prepared by:</strong> {{metadata.preparedBy || 'ShipSec Security Team'}}
  </p>

  <h2>Executive Summary</h2>
  <p style="margin-bottom: 16px;">
    This security assessment was conducted to identify vulnerabilities and security weaknesses
    in the specified targets. A total of <strong>{{findings.length}}</strong> findings were identified.
  </p>

  <div class="summary-grid">
    <div class="summary-card critical">
      <div class="summary-count" style="color: ${SEVERITY_COLORS.critical}">{{#each findings as finding}}{{#if finding.severity === 'critical'}}1{{/if}}{{/each}}</div>
      <div class="summary-label">Critical</div>
    </div>
    <div class="summary-card high">
      <div class="summary-count" style="color: ${SEVERITY_COLORS.high}">{{#each findings as finding}}{{#if finding.severity === 'high'}}1{{/if}}{{/each}}</div>
      <div class="summary-label">High</div>
    </div>
    <div class="summary-card medium">
      <div class="summary-count" style="color: ${SEVERITY_COLORS.medium}">{{#each findings as finding}}{{#if finding.severity === 'medium'}}1{{/if}}{{/each}}</div>
      <div class="summary-label">Medium</div>
    </div>
    <div class="summary-card low">
      <div class="summary-count" style="color: ${SEVERITY_COLORS.low}">{{#each findings as finding}}{{#if finding.severity === 'low'}}1{{/if}}{{/each}}</div>
      <div class="summary-label">Low</div>
    </div>
    <div class="summary-card info">
      <div class="summary-count" style="color: ${SEVERITY_COLORS.info}">{{#each findings as finding}}{{#if finding.severity === 'info'}}1{{/if}}{{/each}}</div>
      <div class="summary-label">Info</div>
    </div>
  </div>

  <div class="page-break"></div>

  <h2>Detailed Findings</h2>
  {{#each findings as finding}}
  <div class="finding {{finding.severity}}">
    <h3>{{finding.title}}</h3>
    <span class="severity-badge {{finding.severity}}">{{finding.severity}}</span>
    {{#if finding.cve}}
    <p style="margin: 8px 0 0 0; font-size: 13px; color: #6b7280;"><strong>CVE:</strong> {{finding.cve}}</p>
    {{/if}}
    {{#if finding.cvss}}
    <p style="margin: 8px 0 0 0; font-size: 13px; color: #6b7280;"><strong>CVSS:</strong> {{finding.cvss}}</p>
    {{/if}}
    <p style="margin: 12px 0 0 0; font-size: 14px; line-height: 1.6; color: #374151;">{{finding.description}}</p>
    {{#if finding.proof}}
    <div style="margin-top: 12px;">
      <strong style="font-size: 13px; color: #374151;">Proof:</strong>
      <pre style="margin: 8px 0; padding: 12px; background: #1f2937; color: #e5e7eb; border-radius: 6px; font-size: 12px; overflow-x: auto;">{{finding.proof}}</pre>
    </div>
    {{/if}}
    {{#if finding.remediation}}
    <div style="margin-top: 12px;">
      <strong style="font-size: 13px; color: #374151;">Remediation:</strong>
      <p style="margin: 8px 0 0 0; font-size: 14px; line-height: 1.6; color: #374151;">{{finding.remediation}}</p>
    </div>
    {{/if}}
  </div>
  {{/each}}

  <div class="page-break"></div>

  {{#if scope.length}}
  <h2>Scope</h2>
  <table>
    <thead>
      <tr>
        <th>Target</th>
        <th>Type</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      {{#each scope as item}}
      <tr style="border-bottom: 1px solid #e5e7eb;">
        <td style="padding: 12px; color: #374151;">{{#if typeof item === 'string'}}{{item}}{{else}}{{item.target}}{{/if}}</td>
        <td style="padding: 12px; color: #6b7280;">{{#if typeof item === 'string'}}-{{else}}{{item.type || '-'}}{{/if}}</td>
        <td style="padding: 12px; color: #6b7280;">{{#if typeof item === 'string'}}-{{else}}{{item.description || '-'}}{{/if}}</td>
      </tr>
      {{/each}}
    </tbody>
  </table>
  {{/if}}

  <h2>Methodology</h2>
  <p style="color: #6b7280;">
    This assessment was conducted following industry-standard penetration testing methodologies
    including OWASP Testing Guide, PTES, and OSSTMM. Testing included automated vulnerability
    scanning, manual testing, and validation of findings.
  </p>
</div>
`;
}
