/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findAll"];
        put?: never;
        post: operations["WorkflowsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_findOne"];
        put: operations["WorkflowsController_update"];
        post?: never;
        delete: operations["WorkflowsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowsController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{runId}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowsController_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkflowRequestDto: {
            id?: string;
            name: string;
            description?: string;
            nodes: {
                id: string;
                type: string;
                label: string;
                position: {
                    x: number;
                    y: number;
                };
                config?: {
                    [key: string]: unknown;
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
        UpdateWorkflowRequestDto: {
            id?: string;
            name: string;
            description?: string;
            nodes: {
                id: string;
                type: string;
                label: string;
                position: {
                    x: number;
                    y: number;
                };
                config?: {
                    [key: string]: unknown;
                };
            }[];
            edges: {
                id: string;
                source: string;
                target: string;
                sourceHandle?: string;
                targetHandle?: string;
            }[];
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compiled workflow definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title?: string;
                        description?: string | null;
                        entrypoint?: {
                            ref?: string;
                        };
                        actions?: {
                            ref?: string;
                            componentId?: string;
                            params?: {
                                [key: string]: unknown;
                            };
                            dependsOn?: string[];
                        }[];
                        config?: {
                            environment?: string;
                            timeoutSeconds?: number;
                        };
                    };
                };
            };
        };
    };
    WorkflowsController_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow execution result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Execution run identifier */
                        runId?: string;
                        /** @description Outputs keyed by node reference */
                        outputs?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    WorkflowsController_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace events for a workflow run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runId?: string;
                        events?: {
                            type?: string;
                            nodeRef?: string;
                            /** Format: date-time */
                            timestamp?: string;
                            message?: string;
                            error?: string;
                            outputSummary?: Record<string, never>;
                        }[];
                    };
                };
            };
        };
    };
}
